### ISSUE TITLE
504 Gateway Time-out when connecting to /sparkpi

### ISSUE THREAD

**Issue by SamiSousa** [radanalyticsio/tutorial-sparkpi-python-flask#12]
Followed all the steps listed in the readme. Root displays message fine, but /sparkpi gives a timeout. This also causes all other requests to the server to timeout. Perhaps the call to the spark cluster should be made asynchronously.

**Comment by elmiko** [comment]
hi @SamiSousa, yes migrating this application to an asynchronous model is something I have considered in the past. For the sake of having a simple code base in the tutorial I never added it. My concern is that with an async model we would need to change the server to be more resource oriented (ie make a Pi request, get an id, poll for the status of the id).

I'm wondering what the error log from the application looks like from your 504 example?

There have been several refinements to this application over time to account for various threading issues and I am always curious to see a new breakage ;)

**Comment by SamiSousa** [comment]
Hi @elmiko, thanks for getting back to me. I found out the issue wasn't with the application but that the spark cluster needed more resources to run properly. Will close this issue.

**Comment by elmiko** [comment]
ah, cool. thanks for the update @SamiSousa !
